# Generated by Django 3.0 on 2020-08-29 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourPlan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정시간')),
            ],
        ),
    ]
