# Generated by Django 3.0 on 2020-08-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourPlan', '0004_plan_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
