# Generated by Django 3.0 on 2020-10-03 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourPlan', '0009_plan_scrap_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='users',
        ),
        migrations.AddField(
            model_name='plan',
            name='scrap_users',
            field=models.ManyToManyField(related_name='scrap_plans', through='tourPlan.Scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
