# Generated by Django 3.0 on 2020-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourPlan', '0010_auto_20201003_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='password',
            field=models.IntegerField(default=0),
        ),
    ]
