# Generated by Django 3.0 on 2020-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourPlan', '0011_plan_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
