# Generated by Django 3.0 on 2020-09-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_auto_20200904_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
