# Generated by Django 3.0 on 2020-10-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_auto_20200930_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date']},
        ),
    ]
