# Generated by Django 3.0 on 2020-10-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_auto_20201001_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time']},
        ),
    ]
