# Generated by Django 3.0 on 2020-09-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
